# Change these first
owner: linkwaveconnect # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.linkwaveconnect.com.br
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: LinkWave Status
  introTitle: "Status page for all LinkWave related websites"
  introMessage: This is the LinkWave's Status page for every service that linkwave offers
  navbar:
    - title: LinkWave Status
      href: /
    - title: Main Site
      href: https://linkwaveconnect.com.br

i18n:
  footer: All rights reserved - LinkWave Connect LTDA | Todos os direitos reservados - LinkWave Connect LTDA - CNPJ: 53.108.042/0001-07

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
