# Change these first
owner: linkwaveconnect # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.linkwaveconnect.com.br
  # baseUrl: /your-repo-name
  logoUrl: https://search.linkwaveconnect.com.br/assets/images/doogleLogo.png
  name: LinkWave Status
  introTitle: "Status page for all LinkWave related websites"
  introMessage: Página de status para todos os serviços da LinkWave
  theme: ocean
  navbar:
    - title: LinkWave Status
      href: /
    - title: Main Site
      href: https://linkwaveconnect.com.br

i18n:
  footer: "All rights reserved | Todos os direitos reservados - LinkWave Connect LTDA - CNPJ: 53.108.042/0001-07"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
